### Аннотация

Ноутбук составлен на основе материалов [[1]](https://github.com/SciProgCentre/python-scientific-book/blob/master/pages/StudentEdition/05.ipynb), [[2]](https://github.com/SciProgCentre/python-scientific-book/blob/master/pages/StudentEdition/07.ipynb)





## Создание Numpy массивов

# NumPy


In [1]:

import numpy as np
a = np.array([1, 2, 3], float) # Однмемерный массив из списка 
b = np.repeat(-1. ,10) # Массив полученные повоторением исходного объекта
c = np.zeros((3, 5)) # Матрица из нулей размера 3х5
d = np.ones((2, 2, 2)) # Трехмерный массив из единиц
e = np.eye(5) # Единичная матрица
print(a, b, c, d, e, sep='\n\n')
print(c.shape) # Возвращает размерность массива, для двумерного это количество строк и столбцов

[1. 2. 3.]

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(3, 5)


## Арифметические операции с массивами  и векторизация



Полезной особенностью numpy-массивов является так называемая _векторизация_ --- возможность делать быстрые поэлементные операции с массивами без использования цикла `for`.

In [2]:
a = np.array([1, 4, 3], float)
b = np.array([5, 2, 6], float)
print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(a % b)
print(b ** a)
print(np.sqrt(a))
print(np.sum(a))
print(np.prod(b))
print(a.dot(b)) # Скалярное произведение
print(b > a)
print(np.where(a != 2, 1/a, a))

[6. 6. 9.]
[-4.  2. -3.]
[ 5.  8. 18.]
[5.  0.5 2. ]
[1. 0. 3.]
[  5.  16. 216.]
[1.         2.         1.73205081]
8.0
60.0
31.0
[ True False  True]
[1.         0.25       0.33333333]


## Линейная алгебра

NumPy также предоставляет набор встроенных функций и методов для работы с линейной алгеброй. Это всё можно найти в под-модуле `linalg`.

In [3]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
b = a.T # Транспонированый массив
print(np.linalg.det(a)) # Ищем детерминант 
vals, vecs = np.linalg.eig(a)
print(vals)
print(vecs)

-48.00000000000003
[ 8.85591316  1.9391628  -2.79507597]
[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


## Операции с индексами 
Оперативная память компьютера линейна, и поэтому даже многомерные массивы, на самом деле являются некоторыми линейными структурами, над которыми существуют система индексов, говорящих как именно читать этот линейный блок. Проведение операций над индексами в большистве случаев эффективно и поэтому операции смены размерности массива или транспонирования выполняются быстро

In [4]:
a = np.asarray([[1, 2], [3, 4]])
b = a.T # Транспонированый массив
print(b)

[[1 3]
 [2 4]]


In [5]:
b[0, 0] = 10
print(b)

[[10  3]
 [ 2  4]]


In [6]:
print(a)

[[10  2]
 [ 3  4]]


Как мы видим при изменени переменной `b` изменилась переменная `a`. Это произошло потому, что обе эти переменные использубют один и тот же кусок памяти, но по разному 

## Срезы

В numpy реализован удобный способ работы с элементами матрицы. Он позволяет пройтись по элементам с определенным шагом и в определенном направлении.

Пусть у нас есть двумерная матрица. Стоит запомнить следущий синтаксис:
- `[:]` -- получить все элементы матрицы
- `[:, 0]` -- получить первый столбец матрицы
- `[2, :]` -- получить третью строку матрицы
- `[-2, :]` -- получить вторую строку матрицы с конца
- `[::3, 0]` -- получить каждый третий элемент из первой строки
- `[1:-1:3, 0]`-- получить каждый третий элемент первой строки начиная со второго и, возможно, закнчивая предпоследним

In [7]:
array = np.array([i for i in range(0, 81*4, 4)])
print(array, array.shape, "\n", sep="\n\n")

matrix = array.reshape(9, 9)
print(matrix, matrix.shape, "\n", sep="\n\n")

print(matrix[::2, ::2], "\n")

print((matrix[::3, ::3] + matrix[::3, ::3].T) / 50, "\n")

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140
 144 148 152 156 160 164 168 172 176 180 184 188 192 196 200 204 208 212
 216 220 224 228 232 236 240 244 248 252 256 260 264 268 272 276 280 284
 288 292 296 300 304 308 312 316 320]

(81,)



[[  0   4   8  12  16  20  24  28  32]
 [ 36  40  44  48  52  56  60  64  68]
 [ 72  76  80  84  88  92  96 100 104]
 [108 112 116 120 124 128 132 136 140]
 [144 148 152 156 160 164 168 172 176]
 [180 184 188 192 196 200 204 208 212]
 [216 220 224 228 232 236 240 244 248]
 [252 256 260 264 268 272 276 280 284]
 [288 292 296 300 304 308 312 316 320]]

(9, 9)



[[  0   8  16  24  32]
 [ 72  80  88  96 104]
 [144 152 160 168 176]
 [216 224 232 240 248]
 [288 296 304 312 320]] 

[[0.  2.4 4.8]
 [2.4 4.8 7.2]
 [4.8 7.2 9.6]] 



## Чтение даных

Numpy также предоставляет функционал для чтения данных, который бывает весьма полезен

In [8]:
!cat data/data.txt

cat: data/data.txt: No such file or directory


In [9]:
data = np.loadtxt('./data/data.txt')
data

OSError: ./data/data.txt not found.

## Задание по numpy

1. Создайте вектор с элементами от 1 до 99 включительно
2. Выведите все значения с шагом 3
3. Посчитайте сумму троек элементов из предыдущего пункта
4. Сделайте `reshape` для массива из предыдущего пункта в матрицу размера 11х3
5. Транспонируйте матрицу из предыдущего пункта
6. Произведите векторное умножение матрицы из предыдущего пункта на вектор размерности 11 из элементов от -9 до 2
7. Запишите срез матрицы из пункта `5` в файл `matrix.dat`. Срез должен включать в себя 1, 5, 9 столбцы и 0 и 2 строки. **Подсказка**: требуется вписать элементы матрицы, которая состоит из пересечения соответсвующих столбцов и строк.
8. Посчитайте детерминант матрицы, которая содержит в себе строки 2, 5, 8 из матрицы пункта `4`.
9. `*`Создайте два вектора длины 10. Элементы первого вектора -- первые 10 простых чисел со знаком минус, второго вектора -- первые 10 чисел последовательности Фибоначчи. Посчитайте скалярное произведение двух векторов. **Указание**: для получения простых чисел и чисел из последовательности Фибоначчи реализуйте функции `prime_number` и `fibonacci_number`.
10. `*`Реализуйте функцию вычисления матричной экспоненты
$e^X = \sum\limits_{k = 0}^{n} \frac{1}{k!} X^k$, $X^k$ -- матрица $X$ в степени $k$, $X^0 = I$

Замечания:
- Пункты `*` реализуются по завршению блока заданий на `matplotlib`.
- Задания делать внутри следующей ячейки ноутбука. Если работаете в Pycharm, то сохраняйте в файлы `numpy_i.py`, где `i` указывает пункт задания.
- Задания, или готовый ноутбук, сохранять в директории (папке) `classwork04`. **Никак иначе диеректорию не называть!**

In [31]:
import numpy as np

def prime_number(n): #первые n простых чисел
    numbers = [-2]
    lenth = 1
    i = 3
    while True:
        flag = True
        j = 2
        while j<int(i**0.5)+1:
            if i % j == 0:
                flag = False
            j+=1
        if flag:
            numbers.append(-i)
            lenth += 1
        if n == lenth:
            return numbers
        i+=2
def fibonacci_number(n): #первые n чисел фибоначи
    numbers = [1,1]
    lenth = 2
    for i in range(n-2):
      numbers.append(numbers[-1]+numbers[-2])
    return numbers
#X @ Y matrichnoe umnojenie
#1
array = np.array(range(1,100))
#2
array_1 = array[::3]
array_2 = array[1::3]
array_3 = array[2::3]
#print(array_1)
#3
total_vector = array_1 + array_2 + array_3
#print(total_vector)
#4
total_vector_reshaped = total_vector.reshape(11,3)
#print(total_vector_reshaped)
#5
total_vector_T = total_vector_reshaped.T
#print(total_vector_T)
#6
X = np.array(range(-9,2)).reshape(11,1)
#print(X)
prod = total_vector_T @ X
#print(prod)
#8
det = np.linalg.det(total_vector_reshaped[2::3])
#print(det)
#9
A = np.array(prime_number(10))
B = np.array(fibonacci_number(10))
C = A @ B
#print(C)
#10
X = np.array([[1,0,0],[2,3,4],[4,5,6]])

import numpy as np

def fact(k):
  if k == 0:
    return 1
  return k*fact(k-1)

def X_(k, X=X):
    if k == 1:
        return X
    return X @ X_(k-1, X)

def e_(X,k=0,n=100):
    while k<=n:
        if k == 0:
            final_array = np.eye(*X.shape)
            k+=1
        else:
            final_array += np.array((1/fact(k))*(X_(k, X)))
            k+=1
        if k == n:
            return final_array
        
print(e_(X))

[[2.71828183e+00 0.00000000e+00 0.00000000e+00]
 [2.91014404e+03 3.43137095e+03 4.26547076e+03]
 [4.52471617e+03 5.32424804e+03 6.62289932e+03]]


In [35]:
X = np.eye(3)
e_(-X)

array([[0.36787944, 0.        , 0.        ],
       [0.        , 0.36787944, 0.        ],
       [0.        , 0.        , 0.36787944]])

In [34]:
np.exp(-1)

0.36787944117144233

# Matplotlib

# Построение графиков

Для построения графиков чаще всего используется `matplotlib.pyplot`. Больше информации можно найти по этим ссылкам:
* [Научная графика в python](https://nbviewer.jupyter.org/github/whitehorn/Scientific_graphics_in_python/tree/master/) --- уроки по `matplotlib` на русском языке.
* [Галерея  `matplotlib`](https://matplotlib.org/3.1.1/gallery/index.html) --- галерея примеров на официальном сайте `matplotlib`, выбираете нужный вам пример и смотрите как он сделан.

Построить график достаточно просто:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

x = np.linspace(-1, 1)  # Создаем массив из ста точек на промежутке (-1; 1)
y = x**3
plt.plot(x,y)

Как вы можете заметить построеный график хорош всем, кромо того обстоятельства что он нарушает все правила оформления графиков для лабораторных работ. Постораемся оформить его. 
Следующая иллюстрация поможет нам узнать как называются элементы изображения:


![](https://matplotlib.org/_images/anatomy.png)


Используя поиск по сайту [matplotlib.org](https://matplotlib.org/3.1.1/index.html) можно подробно узнать как настроить тот или иной элемент изображения. А мы приведем краткое описание полезных функции:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['font.size'] = 16 # Управление стилем, в данном случаем - размером шрифта 
 # Создаем фигуру
plt.figure(figsize=(7,7))

# Подписываем оси и график
plt.title(r"Это название  графика  $y = x^3$ - да, можно использовать LaTeX:")
plt.ylabel("Это ось Y")
plt.xlabel(r"Это ось X, $F(x) = \int f(x) dx + C$")



# Добавляем данные
x = np.linspace(-1,1,100)
y = x**3
plt.plot(x,y, label="Синия линия")

# Еще данные
x2 = x[::10]
y2 = np.sin(x2)
plt.plot(x2,y2, 'r^', label='Красные треугольники')
# 'r^' - задает стиль линии - красные (red) треугольники (^), подробнее в документации

# Данные с ошибками
mu = np.sin(x2)
sigma = np.abs(mu)**0.5
y2 = np.random.normal(mu, sigma)
# Можно рисовать ошибки
plt.errorbar(x2,y2, yerr=sigma, xerr=0.1, fmt='.', label='Кресты') 

# Активируем сетку
plt.grid(b=True, which='major', axis='both', alpha=1)
plt.grid(b=True, which='minor', axis='both', alpha=0.5)

# Активируем легенду графика
plt.legend()
# Внимание, запускаете вашу программу как сценарий, то что бы показать график
# Используйте эту команду
# plt.show()
# Сохраняем изображение в текущую директорию
plt.savefig('example.png')

In [ ]:
# Логарифмический масштаб по оси x (аналогично для y)
plt.xscale('log')
plt.yscale('log')
# Сетка
plt.grid(True)
# Добавляем данные
x = np.linspace(0,100,100)
y = x**3
plt.plot(x,y,"k--", label="Синия линия") # "k--" --- черная прерывистая линия

## Общие замечания

1. Не советуется сильно изменять стандартный размер фигуры, который равен `[6.4, 4.8]`. Тогда не потребуется подстраивать раземер шрифта.
2. Попробуйте воспользоваться функцией `plt.tight_layout()`. Она *уберет* лишнее пустое пространство вокруг графика.
3. Для передачи *сырых* строк стоит пользоваться `r"my favorite $\LaTeX$"` $\rightarrow$ my favorite $\LaTeX$
4. Для сохранения графиков можно воспользоваться функцией `plt.savefig()`. По умолчанию возможно сохранять в `.pdf/.jpg/.png` и так далее.

## Задание matplotlib

1. Нарисуйте точками график $\sin(x) x^{-2}$ для x со значениями от 0 до 100 с шагом 10
2. Добавьте сетку и описание осей для предыдущего графика
2. Нарисуйте непрерывной прямой график $e^{-x \sin(x)}$ для x со значениями от 10 до 100
3. Добавьте сетку и описание осей для предыдущего графика
4. Добавьте мелкую сетку для предыдущего графика (опция `plt.minorticks_on()`
5. Нарисуйте точками график $e^{x \sin(x)}$ для x со значениями от 10 до 100
6. 
7. Сделайте логарифмический масштаб по оси ординат. Отразите этот факт в подписи к оси
8. Добавьте легенду точкам и подписи к графику

Замечания:
- Если указано сделать подпись осей, то нужно добавить подписи к двум осям графика
- Если указано ссделать подписи к графику, то нужно добавить оглавление графика, легенду для точек и кривых, подписи к осям
- Задания делать внутри следующей ячейки ноутбука. Если работаете в Pycharm, то сохраняйте в файлы `matplotlib_i.py`, где `i` указывает пункт задания.
- Задания, или готовый ноутбук, сохранять в директории (папке) `classwork04`. **Никак иначе диеректорию не называть!**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import math


#2
plt.figure()
plt.grid(True)

plt.title('График 1')
plt.ylabel('Y')
plt.xlabel('X')
#1
x1 = np.linspace(0,100,10)
y1 = [math.sin(x)*x**(-2) for x in x1]
plt.plot(x1,y1, 'b', label='sin(x)*x**(-2)')

#3
plt.figure()

#4
plt.grid(True)
plt.title('График 2')
plt.ylabel('Y, log')
plt.xlabel('X')

#5
plt.minorticks_on()

#6
x2 = np.linspace(10,100, 1000)
y2 = [math.exp(x)**(-x*math.sin(x)) for x in x2]
plt.plot(x2,y2, 'r', label='exp(x)**(-x*sin(x)')

#8
plt.yscale('log')

#9
plt.legend()


## Data Analysis

Функция `fake_data_generator` выдает данные какого-то эксперимента. Но это не беда, ведь мы всегда можем обработать данные!

Узнайте свой порядковый номер в группе и с помощью функции `get_numbers` получите свои входные значения для функции `fake_data_generator`.

Полученные  экспериентальные данные используйте для нанесения на график. Затем попрбуйте *прикинуть* параметры прямой, которая могла бы проходить через экспериентальные точки.

### План действий

1. Сгенерируйте свои числа для задачи
2. Нанесите точки на график. В качестве ошибок по `x` используйте половину расстояния между соседними точками. Для ошибок по `y` используйте корень квадратный от модуля значения. Добавьте легенду "DATA"
3. Нанесите сетку на график
4. Выделите штрихованную прямую синего цвета, которая выделяет средний уровень точек по оси абсцисс. Добавьте легенду со значением среднего "mean x = "
5. Выделите штрих-пунктирную прямую красного цвета, которая выделяет средний уровень точек по оси ординат. Добавьте легенду со значением среднего "mean y = "
6. Нарисуйте черным цветом прямую, которая примерно описывает данные на графике. Добавьте легенду "fit"
7. Точки пересечения подгоночной кривой и средних значений выделить синим цветом
8. Добавить описание для оси абсцисс $\xi, cm\rightarrow$ `$\xi, cm$`
9. Добавить описание для оси ординат $\rho, mm^{-3}\rightarrow$`$\rho, mm^{-3}$`
10. Легенду разместите в правом нижнем углу или же в верхнем правом

In [ ]:
import matplotlib
from matplotlib import pyplot as plt

matplotlib.rcParams.update(matplotlib.rcParamsDefault)


def get_numbers(student):
    return student, (student + 4) % 5 + 3, student % 2 * 10 + 12, (student % 5 * 3 + 7) * 3 

def fake_data_generator(seed, vmin=0, vmax=10, size=100):
    import numpy as np
    np.random.seed(seed)
    data = np.random.randint(vmin, vmax, size=20)
    mean = data.mean()
    std = data.std()
    noise = np.random.normal(loc=mean, scale=std**.5, size=size)
    fake_x = np.array([-5 + i * 20 / size for i in range(size)])
    
    linear = lambda x, k=(.5 - np.random.rand()) * 15, b=np.random.rand()*10: k * x + b
    linear_data = linear(fake_x)
    fake_y = linear_data + noise
    return fake_x, fake_y

In [ ]:
#sdelano v classwork05
